import { adminApi } from './admin-api.js';

const app=document.querySelector('#admin-app');
const nav=[['overview','Огляд','⌁'],['students','Учні','◎'],['teachers','Викладачі','◈'],['guardians','Батьки','◇'],['groups','Групи','⬡'],['classes','Заняття','◷'],['homework','Домашні роботи','▤'],['projects','Проєкти','△'],['portfolios','Портфоліо','▣'],['mentoring','Менторство','∞'],['reports','Звіти','◫'],['notifications','Сповіщення','⌁'],['users','Користувачі','◉'],['system','Система','▦'],['security','Безпека','◆']];
const titles=Object.fromEntries(nav.map(([id,label])=>[id,label]));
const state={data:null,route:'overview',explorer:{entity:'users',page:1,pageSize:25,sort:'id',direction:'asc',q:''},explorerData:null,attendance:null};
const esc=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmt=value=>value?new Intl.DateTimeFormat('uk-UA',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(value)):'—';
const status=value=>`<span class="status status--${esc(value)}">${esc({active:'Активний',disabled:'Вимкнений',archived:'Архів',scheduled:'Заплановано',completed:'Завершено',cancelled:'Скасовано',rescheduled:'Перенесено',published:'Опубліковано',draft:'Чернетка',ready_for_review:'Очікує погодження',approved:'Погоджено',sent:'Надіслано',failed:'Помилка',pending:'Очікує',confirmed:'Підтверджено',private:'Приватне',shareable:'За посиланням',public:'Публічне',ok:'Готово',warning:'Перевірити',required:'Потрібно'}[value]||value||'—')}</span>`;
const progress=value=>`<div class="progress"><i style="width:${Math.max(0,Math.min(100,Number(value)||0))}%"></i></div>`;
const cell=value=>Array.isArray(value)?value.map(item=>`<span class="pill">${esc(item)}</span>`).join(' '):typeof value==='object'&&value!==null?`<span class="code">${esc(JSON.stringify(value))}</span>`:esc(value??'—');
const empty=(title,text)=>`<div class="empty"><strong>${esc(title)}</strong><p>${esc(text)}</p></div>`;

function shell(content){const d=state.data;return `<div class="admin-shell"><aside class="sidebar" id="sidebar"><div class="brand"><span class="brand-mark">AI</span><span>STARTUP SCHOOL<small>ADMIN CONTROL CENTER</small></span></div><nav>${nav.map(([id,label,icon])=>`<a href="#${id}" class="${state.route===id?'active':''}"><b>${icon}</b><span>${label}</span></a>`).join('')}</nav><div class="side-profile"><span class="avatar">${esc(d.admin.name.split(/\s+/).map(x=>x[0]).slice(0,2).join(''))}</span><span><strong>${esc(d.admin.name)}</strong><small>ADMIN · захищений доступ</small></span></div></aside><main class="workspace"><header class="topbar"><div><span class="eyebrow">AI STARTUP SCHOOL · OPERATIONS</span><h1>${esc(titles[state.route]||'Огляд')}</h1></div><div class="top-actions"><button class="search-button" data-action="search">⌕ Пошук у школі</button><button class="icon-button" data-action="logout">Вийти</button><button class="icon-button mobile-menu" data-action="menu">☰</button></div></header><div class="page">${content}</div></main></div><div class="modal-layer" id="modal"></div><div class="search-layer" id="search"><div class="search-box"><input id="global-search" placeholder="Учень, викладач, група, заняття або проєкт" maxlength="80"><div class="search-results" id="search-results"><p>Введіть щонайменше 2 символи.</p></div></div></div><div class="toast" id="toast"></div>`}
function table(headers,rows){return `<div class="table-wrap"><table><thead><tr>${headers.map(item=>`<th>${esc(item)}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`}
function intro(text,extra=''){return `<div class="intro"><p>${esc(text)}</p>${extra||'<span class="live"><i></i> Дані захищеного backend</span>'}</div>`}

function overview(){const d=state.data,m=d.metrics;const cards=[['Активні учні',m.activeStudents,'операційний реєстр'],['Активні групи',m.activeGroups,'навчальні потоки'],['Викладачі',m.teachers,'активні профілі'],['Заняття сьогодні',m.classesToday,`${m.upcomingClasses} попереду`],['Очікують перевірки',m.awaitingReview,`${m.needsRevision} на доопрацюванні`],['Звіти',m.reportsAwaiting,'очікують погодження']];return shell(`${intro('Операційний стан школи без рейтингів дітей і vanity-метрик.')}<div class="metrics">${cards.map(([label,value,note])=>`<div class="metric"><span>${label}</span><strong>${value}</strong><small>${note}</small></div>`).join('')}</div><div class="grid-2"><section class="panel"><div class="panel-head"><div><span class="kicker">ОПЕРАЦІЙНА ЧЕРГА</span><h2>Потребує дії</h2></div><span>оновлено зараз</span></div><div class="queue">${d.homework.filter(x=>Number(x.submissions)>Number(x.reviews)).slice(0,4).map(x=>`<a href="#homework"><span class="avatar">ДЗ</span><span><strong>${esc(x.title)}</strong><small>${esc(x.group)} · ${x.submissions-x.reviews} неперевірених</small></span><em>Перевірка</em></a>`).join('')}${d.reports.filter(x=>x.status==='ready_for_review').map(x=>`<a href="#reports"><span class="avatar">ЗВ</span><span><strong>${esc(x.studentFirstName)}</strong><small>Тижневий звіт очікує погодження</small></span><em>Звіт</em></a>`).join('')||''}${d.students.filter(x=>Number(x.absences)>0).map(x=>`<a href="#students"><span class="avatar">${esc(String(x.name).slice(0,1))}</span><span><strong>${esc(x.name)}</strong><small>${x.absences} проблеми відвідування</small></span><em>Увага</em></a>`).join('')||''}</div></section><aside class="panel"><div class="panel-head"><div><span class="kicker">КОНФІГУРАЦІЯ</span><h2>Production readiness</h2></div><button class="text-button" data-go="security">Деталі →</button></div><div class="health-list">${Object.entries(d.health).slice(0,7).map(([key,item])=>`<div class="health-row"><span><strong>${esc(key)}</strong><small>${esc(item.label)}</small></span>${status(item.status)}</div>`).join('')}</div></aside></div><div class="grid-3">${[['Менторські зустрічі',m.mentorBookings,'mentoring'],['Проблеми відвідування',m.attendanceIssues,'classes'],['Портфоліо milestones',m.portfolioMilestones,'portfolios']].map(([label,value,route])=>`<button class="metric" data-go="${route}"><span>${label}</span><strong>${value}</strong><small>Відкрити операційний контекст →</small></button>`).join('')}</div>`)}

function students(){const rows=state.data.students.map(x=>`<tr><td><strong>${esc(x.name)}</strong><small class="code">${esc(x.id)}</small></td><td>${esc(x.group)}</td><td><strong>${x.progress}%</strong>${progress(x.progress)}</td><td>${x.xp} XP<small>${esc(x.level)} · streak ${x.streak}</small></td><td>${x.submissions??x.homework?.submitted??0}<small>${x.absences??x.attendance?.absent??0} пропусків</small></td><td>${status(x.status)}</td><td class="actions"><button class="text-button" data-action="account" data-id="${x.id}" data-status="${x.status==='active'?'disabled':'active'}">${x.status==='active'?'Вимкнути':'Увімкнути'}</button></td></tr>`);return shell(`${intro('Пошук і підтримка учнів з мінімально потрібними персональними даними.')}<div class="toolbar"><input data-filter placeholder="Фільтр за імʼям або групою"><select><option>Усі статуси</option><option>Активні</option><option>Вимкнені</option></select></div>${table(['Учень','Група','Прогрес','Рівень','Навчання','Статус',''],rows)}`)}
function teachers(){const rows=state.data.teachers.map(x=>`<tr><td><strong>${esc(x.name)}</strong><small>${esc(x.title)}</small></td><td>${x.groups}</td><td>${x.upcomingClasses}</td><td>${x.classesTaught}</td><td>${x.reviews}</td><td>${x.mentor?'Ментор':'—'}</td><td>${status(x.status)}</td></tr>`);return shell(`${intro('Навантаження, призначення і стан облікових записів викладачів.')} ${table(['Викладач','Групи','Майбутні','Проведено','Перевірки','Роль','Статус'],rows)}`)}
function guardians(){const rows=state.data.guardians.map(x=>`<tr><td><strong>${esc(x.name)}</strong><small class="code">${esc(x.id)}</small></td><td>${cell(x.linkedStudents)}</td><td>${status(x.relationshipStatus)}</td><td>${x.telegramLinked?'Підключено':'Не підключено'}</td><td>${status(x.status)}</td><td class="actions">${x.relationshipStatus==='active'?`<button class="danger" data-action="revoke-guardian" data-id="${x.linkId}">Відкликати звʼязок</button>`:''}</td></tr>`);return shell(`${intro('Батьківський доступ існує лише через явний активний звʼязок з учнем.')} ${table(['Батьки','Повʼязані учні','Звʼязок','Telegram','Акаунт',''],rows)}`)}
function groups(){const rows=state.data.groups.map(x=>`<tr><td><strong>${esc(x.name)}</strong><small class="code">${esc(x.id)}</small></td><td>${esc(x.courseTitle)}</td><td>${esc(x.teachers||'Команда викладачів')}</td><td>${x.studentCount}</td><td>${fmt(x.startsOn)}<small>до ${fmt(x.endsOn)}</small></td><td>${status(x.status||'active')}</td></tr>`);return shell(`${intro('Групи, курси, викладачі та календарний контекст.')} ${table(['Група','Курс','Викладачі','Учні','Період','Статус'],rows)}`)}
function classes(){const rows=state.data.sessions.map(x=>`<tr><td><strong>${esc(x.title)}</strong><small class="code">${esc(x.id)}</small></td><td>${esc(x.group)}</td><td>${esc(x.teacher)}</td><td>${fmt(x.startsAt)}<small>${Math.round(x.durationMinutes)} хв</small></td><td>${status(x.status)}</td><td>${esc(x.meetingProvider)}</td><td>${x.attendanceComplete?status('completed'):status('warning')}</td></tr>`);return shell(`${intro('Інспекція розкладу й аудовані корекції відвідування.')} ${table(['Заняття','Група','Викладач','Час','Статус','Провайдер','Відвідування'],rows)}<section class="panel" style="margin-top:16px"><div class="panel-head"><div><span class="kicker">ВІДВІДУВАННЯ</span><h2>Останні підтвердження</h2></div><span>корекції потребують причини</span></div><div id="attendance-table">${empty('Завантаження','Отримуємо безпечну сторінку записів.')}</div></section>`)}
function homework(){const rows=state.data.homework.map(x=>`<tr><td><strong>${esc(x.title)}</strong><small class="code">${esc(x.id)}</small></td><td>${esc(x.group)}</td><td>${esc(x.teacher||'—')}</td><td>${status(x.status)}</td><td>${fmt(x.dueAt)}</td><td>${x.submissions}</td><td>${x.reviews}</td><td>${x.revisions}</td></tr>`);return shell(`${intro('Операційна видимість без підміни щоденного workflow викладача.')} ${table(['Завдання','Група','Викладач','Стан','Дедлайн','Роботи','Перевірено','Доопрацювання'],rows)}`)}
function projects(){const rows=state.data.projects.map(x=>`<tr><td><strong>${esc(x.title)}</strong><small class="code">${esc(x.id)}</small></td><td>${esc(x.student)}</td><td>${esc(x.stage)}</td><td><strong>${x.progress}%</strong>${progress(x.progress)}</td><td>${cell(x.technologies)}</td><td>${status(x.status)}</td></tr>`);return shell(`${intro('Проєкти відображають прогрес і навички без рейтингу учнів.')} ${table(['Проєкт','Учень','Етап','Прогрес','Технології','Статус'],rows)}`)}
function portfolios(){const rows=state.data.portfolios.map(x=>`<tr><td><strong>${esc(x.title)}</strong><small class="code">${esc(x.id)}</small></td><td>${esc(x.student)}</td><td>${x.items}</td><td><span class="visibility visibility--${esc(x.visibility)}">${esc(String(x.visibility).toUpperCase())}</span></td><td class="actions"><button class="text-button" data-action="portfolio" data-id="${x.id}" data-value="${x.visibility}">Змінити видимість</button></td></tr>`);return shell(`${intro('PRIVATE є типовим станом. SHAREABLE і PUBLIC потребують явної підтвердженої дії.')}<div class="security-banner"><b>PRIVACY BY DEFAULT</b><p>Зміна стану не створює публічний endpoint автоматично й завжди записується в аудит.</p></div>${table(['Портфоліо','Учень','Роботи','Видимість',''],rows)}`)}
function mentoring(){const rows=state.data.mentorBookings.map(x=>`<tr><td><strong>${esc(x.mentor||x.mentorName)}</strong></td><td>${esc(x.student||x.studentName)}</td><td>${fmt(x.startsAt)}</td><td>${status(x.status)}</td><td>${x.meetingUrl?'Авторизоване HTTPS-посилання':'—'}</td></tr>`);return shell(`${intro('Бронювання, переноси й конфлікти часу без розкриття зайвих даних.')} ${table(['Ментор','Учень','Час','Статус','Зустріч'],rows)}`)}
function reports(){const rows=state.data.reports.map(x=>`<tr><td><strong>${esc(x.studentFirstName)}</strong><small class="code">${esc(x.id)}</small></td><td>${esc(x.periodStart)} — ${esc(x.periodEnd)}</td><td>${status(x.status)}</td><td>${x.guardianRelationshipActive?'Активний звʼязок':'Немає звʼязку'}</td><td>${fmt(x.approvedAt)}</td><td class="actions">${['approved','sent','failed'].includes(x.status)&&x.guardianRelationshipActive?`<button class="secondary" data-action="resend-report" data-id="${x.id}">Повторити надсилання</button>`:''}</td></tr>`);return shell(`${intro('Надсилання дозволене лише після погодження і повторної перевірки guardian relationship.')} ${table(['Учень','Період','Статус','Одержувач','Погоджено',''],rows)}`)}
function notifications(){const rows=state.data.notifications.map(x=>`<tr><td><strong>${esc(x.category)}</strong><small class="code">${esc(x.id)}</small></td><td>${esc(x.recipient)}</td><td>${fmt(x.scheduledAt)}</td><td>${status(x.status)}</td><td>${x.attempts}</td><td>${fmt(x.sentAt)}</td></tr>`);return shell(`${intro('Безпечна проєкція outbox без payload, токенів і provider secrets.')} ${table(['Категорія','Одержувач','Заплановано','Статус','Спроби','Надіслано'],rows)}`)}
function users(){const people=[...state.data.students.map(x=>({...x,role:'student'})),...state.data.teachers.map(x=>({...x,role:'teacher'})),...state.data.guardians.map(x=>({...x,role:'guardian'}))];const rows=people.map(x=>`<tr><td><strong>${esc(x.name)}</strong><small class="code">${esc(x.id)}</small></td><td><span class="pill">${esc(x.role)}</span></td><td>${status(x.status)}</td><td class="actions"><button class="text-button" data-action="account" data-id="${x.id}" data-status="${x.status==='active'?'disabled':'active'}">${x.status==='active'?'Вимкнути':'Увімкнути'}</button></td></tr>`);const sessions=state.data.activeSessions.map(x=>`<tr><td><strong>${esc(x.user)}</strong><small>${esc(x.role)}</small></td><td>${esc(x.provider)}</td><td>${fmt(x.createdAt)}</td><td>${fmt(x.expiresAt)}</td><td>${status(x.status)}</td><td class="actions">${x.status==='active'?`<button class="danger" data-action="revoke-session" data-id="${x.id}">Відкликати</button>`:''}</td></tr>`);return shell(`${intro('Ролі не редагуються через mass assignment. Сесії показані лише як безпечні metadata.')}<section class="panel"><div class="panel-head"><h2>Облікові записи</h2><span>явні domain actions</span></div>${table(['Користувач','Роль','Статус',''],rows)}</section><section class="panel" style="margin-top:16px"><div class="panel-head"><h2>Активні сесії</h2><span>без token hashes</span></div>${table(['Користувач','Провайдер','Створено','Завершення','Стан',''],sessions)}</section>`)}
function security(){const events=state.data.securityEvents.map(x=>`<tr><td>${status(x.severity==='high'?'failed':'warning')}</td><td><strong>${esc(x.type)}</strong><small class="code">${esc(x.correlationId)}</small></td><td>${esc(x.actorId||'system')}</td><td>${fmt(x.createdAt)}</td></tr>`);const audit=state.data.auditEvents.map(x=>`<tr><td><strong>${esc(x.action)}</strong><small>${esc(x.targetType)} · ${esc(x.targetId)}</small></td><td>${esc(x.actor)}</td><td>${cell(x.metadata)}</td><td>${fmt(x.createdAt)}</td></tr>`);return shell(`${intro('Детерміновані security events, незмінний audit trail і safe configuration health.')}<div class="security-banner"><b>ADMIN MFA</b><p>Архітектура очікує MFA/passkey/TOTP від стандартного identity provider. Саморобної MFA немає.</p></div><div class="grid-2"><section class="panel"><div class="panel-head"><h2>Configuration health</h2><span>без secret values</span></div><div class="health-list">${Object.entries(state.data.health).map(([key,item])=>`<div class="health-row"><span><strong>${esc(key)}</strong><small>${esc(item.label)}</small></span>${status(item.status)}</div>`).join('')}</div></section><section class="panel"><div class="panel-head"><h2>Security events</h2><span>${events.length} останніх</span></div>${events.length?table(['Рівень','Подія','Actor','Час'],events):empty('Подій немає','Це не гарантує відсутність ризику; підключіть monitoring.')}</section></div><section class="panel"><div class="panel-head"><h2>Administrative audit</h2><span>append-only application path</span></div>${audit.length?table(['Дія','Actor','Безпечні metadata','Час'],audit):empty('Аудит поки порожній','Перші привілейовані дії зʼявляться тут.')}</section>`)}
function system(){return shell(`${intro('Read-only Data Explorer із server-side pagination, allowlisted sort і masked projections.')}<div class="toolbar"><select id="entity-select">${['users','students','teachers','guardians','groups','courses','modules','lessons','sessions','attendance','homework','submissions','reviews','projects','portfolios','mentor_bookings','reports'].map(x=>`<option ${state.explorer.entity===x?'selected':''}>${x}</option>`).join('')}</select><input id="explorer-search" value="${esc(state.explorer.q)}" placeholder="Пошук у вибраній сутності"><button class="secondary" data-action="explore">Застосувати</button></div><div id="explorer-content">${state.explorerData?explorerTable():empty('Завантаження','Отримуємо лише одну сторінку даних.')}</div>`)}
function explorerTable(){const page=state.explorerData,records=page.records;if(!records.length)return empty('Записів немає','Змініть пошук або виберіть іншу сутність.');const keys=Object.keys(records[0]);return `${table(keys,records.map(record=>`<tr>${keys.map(key=>`<td>${cell(record[key])}</td>`).join('')}</tr>`))}<div class="pager"><span>Сторінка ${page.page} · ${page.total} записів</span><span><button class="secondary" data-action="page" data-page="${page.page-1}" ${page.page<=1?'disabled':''}>←</button> <button class="secondary" data-action="page" data-page="${page.page+1}" ${(page.page*page.pageSize)>=page.total?'disabled':''}>→</button></span></div>`}
function render(){const views={overview,students,teachers,guardians,groups,classes,homework,projects,portfolios,mentoring,reports,notifications,users,system,security};app.innerHTML=(views[state.route]||overview)();bind();if(state.route==='classes')loadAttendance();if(state.route==='system'&&!state.explorerData)loadExplorer();}

function bind(){document.querySelectorAll('[data-go]').forEach(el=>el.onclick=()=>location.hash=el.dataset.go);document.querySelector('[data-action="search"]')?.addEventListener('click',openSearch);document.querySelector('[data-action="menu"]')?.addEventListener('click',()=>document.querySelector('#sidebar')?.classList.toggle('open'));document.querySelectorAll('[data-action]').forEach(el=>{if(['search','menu'].includes(el.dataset.action))return;el.onclick=()=>action(el.dataset.action,el.dataset)});document.querySelector('[data-filter]')?.addEventListener('input',event=>{const term=event.target.value.toLocaleLowerCase('uk');document.querySelectorAll('tbody tr').forEach(row=>row.hidden=!row.textContent.toLocaleLowerCase('uk').includes(term))});}
function toast(message,error=false){const node=document.querySelector('#toast');node.textContent=message;node.className=`toast show${error?' error':''}`;setTimeout(()=>node.className='toast',2600)}
function openModal(title,body,onSubmit,dangerous=false){const layer=document.querySelector('#modal');layer.innerHTML=`<form class="modal"><div class="modal-head"><h2>${esc(title)}</h2><button type="button" class="close">×</button></div>${body}<div class="modal-actions"><button type="button" class="secondary close-button">Скасувати</button><button class="${dangerous?'danger':'primary'}" type="submit">Підтвердити</button></div></form>`;layer.classList.add('open');const close=()=>layer.classList.remove('open');layer.querySelector('.close').onclick=close;layer.querySelector('.close-button').onclick=close;layer.onclick=e=>{if(e.target===layer)close()};layer.querySelector('form').onsubmit=async e=>{e.preventDefault();try{await onSubmit(new FormData(e.target));close();await refresh('Зміну застосовано й записано в аудит')}catch(error){toast(error.message,true)}}}
async function refresh(message){state.data=await adminApi.workspace();render();toast(message)}
async function action(name,data){if(name==='account'){openModal(data.status==='disabled'?'Вимкнути обліковий запис':'Увімкнути обліковий запис',`<p>Активні сесії буде відкликано при вимкненні.</p><label class="field"><span>Причина</span><textarea name="reason" required minlength="3"></textarea></label>`,form=>adminApi.setAccountStatus(data.id,{status:data.status,reason:form.get('reason')}),data.status==='disabled')}
  if(name==='logout'){await adminApi.logout();location.replace('/login.html?next=%2Fadmin.html');return}
  if(name==='revoke-guardian')openModal('Відкликати звʼязок з учнем',`<p>Батьківський доступ припиниться одразу. Історія залишиться.</p><label class="field"><span>Причина</span><textarea name="reason" required minlength="3"></textarea></label>`,form=>adminApi.revokeGuardianLink(data.id,form.get('reason')),true);
  if(name==='portfolio')openModal('Видимість портфоліо',`<label class="field"><span>Новий стан</span><select name="visibility"><option value="private">PRIVATE</option><option value="shareable">SHAREABLE</option><option value="public">PUBLIC</option></select></label><label class="field"><span>Причина</span><textarea name="reason" required minlength="3"></textarea></label><p>PUBLIC не створює анонімний endpoint автоматично.</p>`,form=>adminApi.setPortfolioVisibility(data.id,{visibility:form.get('visibility'),reason:form.get('reason')}),true);
  if(name==='resend-report')openModal('Повторити надсилання звіту',`<p>Backend повторно перевірить активний звʼязок із батьками перед створенням outbox event.</p>`,()=>adminApi.resendReport(data.id),true);
  if(name==='revoke-session')openModal('Відкликати сесію',`<label class="field"><span>Причина</span><textarea name="reason" required minlength="3"></textarea></label>`,form=>adminApi.revokeSession(data.id,form.get('reason')),true);
  if(name==='attendance')openModal('Скоригувати відвідування',`<label class="field"><span>Новий стан</span><select name="status"><option value="present">Присутній</option><option value="late">Запізнився</option><option value="absent">Відсутній</option><option value="excused">Поважна причина</option></select></label><label class="field"><span>Обовʼязкова причина корекції</span><textarea name="reason" required minlength="3"></textarea></label>`,form=>adminApi.correctAttendance(data.id,{status:form.get('status'),reason:form.get('reason')}),true);
  if(name==='explore'){state.explorer={...state.explorer,entity:document.querySelector('#entity-select').value,q:document.querySelector('#explorer-search').value,page:1,sort:'id'};state.explorerData=null;await loadExplorer()}
  if(name==='page'){state.explorer.page=Number(data.page);state.explorerData=null;await loadExplorer()}}
async function loadAttendance(){try{const page=await adminApi.explore('attendance',{page:1,pageSize:25,sort:'confirmedAt',direction:'desc'});const node=document.querySelector('#attendance-table');if(!node)return;node.innerHTML=page.records.length?table(['Запис','Статус','Підтверджено',''],page.records.map(item=>`<tr><td><span class="code">${esc(item.id)}</span></td><td>${status(item.status)}</td><td>${fmt(item.confirmedAt)}</td><td class="actions">${String(item.id).includes(':')?'':`<button class="text-button" data-action="attendance" data-id="${item.id}">Коригувати</button>`}</td></tr>`)):empty('Записів немає','Після підтвердження викладачем записи зʼявляться тут.');bind()}catch(error){toast(error.message,true)}}
async function loadExplorer(){try{state.explorerData=await adminApi.explore(state.explorer.entity,state.explorer);render()}catch(error){toast(error.message,true)}}
function openSearch(){const layer=document.querySelector('#search');layer.classList.add('open');const input=layer.querySelector('#global-search');input.focus();layer.onclick=e=>{if(e.target===layer)layer.classList.remove('open')};let timer;input.oninput=()=>{clearTimeout(timer);timer=setTimeout(async()=>{const node=layer.querySelector('#search-results');if(input.value.trim().length<2){node.innerHTML='<p>Введіть щонайменше 2 символи.</p>';return}try{const result=await adminApi.search(input.value.trim());node.innerHTML=result.results.map(item=>`<button><strong>${esc(item.label)}</strong><small>${esc(item.type)} · ${esc(item.meta)}</small></button>`).join('')||'<p>Нічого не знайдено.</p>'}catch(error){node.innerHTML=`<p>${esc(error.message)}</p>`}},220)}}
window.addEventListener('hashchange',()=>{state.route=location.hash.slice(1)||'overview';state.explorerData=null;render()});
async function boot(){try{await adminApi.authenticate();state.data=await adminApi.workspace();state.route=location.hash.slice(1)||'overview';render()}catch(error){if(error.status===401||error.status===403){location.replace('/login.html?next=%2Fadmin.html');return}app.innerHTML=`<div class="fatal"><span class="eyebrow">ADMIN CONTROL CENTER</span><h1>Доступ не відкрито</h1><p>${esc(error.message)}</p><small>Спробуйте оновити сторінку або зверніться до адміністратора.</small></div>`}}
boot();
