import {visibleSessions,sessionFilterButtons} from './session-visibility.js';
import './group-ui.css';
export const escGroup = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date = value => value ? new Date(value).toLocaleString('uk-UA',{timeZone:'Europe/Kyiv',day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}) : 'Не призначено';
const labels={scheduled:'Заплановано',rescheduled:'Заплановано',in_progress:'Триває',completed:'Проведено',cancelled:'Скасовано',archived:'Архівовано'};
const table = (heads,rows) => `<div class="table-wrap"><table><thead><tr>${heads.map(h=>`<th>${escGroup(h)}</th>`).join('')}</tr></thead><tbody>${rows.join('')||`<tr><td colspan="${heads.length}">Поки немає записів</td></tr>`}</tbody></table></div>`;
export function groupFields(group={},teachers=[]){
  const input=(label,name,value,type='text',extra='')=>`<label class="field"><span>${label}</span><input name="${name}" type="${type}" value="${escGroup(value)}" ${extra} required></label>`;
  const days=['Неділя','Понеділок','Вівторок','Середа','Четвер','П’ятниця','Субота'];
  return `<div class="group-form">${input('Назва групи','name',group.name??'','text','maxlength="160"')}
    <div class="form-grid">${input('Навчальний рік','academicYear',group.academicYear??new Date().getFullYear(),'number','min="2000" max="2100"')}${input('Дата старту','startsOn',group.startsOn??new Date().toISOString().slice(0,10),'date')}</div>
    <div class="form-grid">${input('Планова кількість занять','lessonCount',group.lessonCount??0,'number','min="0" max="100"')}${input('Час занять · Київ','time',group.time??'17:00','time')}</div>
    <fieldset><legend>Дні занять</legend><div class="weekday-choices">${[1,2,3,4,5,6,0].map(d=>`<label><input type="checkbox" name="weekdays" value="${d}" ${(group.weekdays??[1,4]).includes(d)?'checked':''}><span>${days[d]}</span></label>`).join('')}</div></fieldset>
    <div class="form-grid"><label class="field"><span>Викладач</span><select name="teacherId" required>${teachers.map(t=>`<option value="${escGroup(t.id)}" ${t.id===group.teacherId?'selected':''}>${escGroup(t.name)}</option>`).join('')}</select></label>
    <label class="field"><span>Статус групи</span><select name="status"><option value="active">Активна</option><option value="archived" ${group.status==='archived'?'selected':''}>Архівна</option></select></label></div>
    <p class="privacy-note">План групи не створює занять автоматично. Кожне заняття потрібно запланувати окремо. Зміна плану групи не змінює дати й статуси вже створених занять.</p></div>`;
}
function formInput(form){return{name:form.get('name'),academicYear:Number(form.get('academicYear')),startsOn:form.get('startsOn'),lessonCount:Number(form.get('lessonCount')),weekdays:form.getAll('weekdays').map(Number),time:form.get('time'),teacherId:form.get('teacherId'),status:form.get('status')};}
export function groupContent(detail,tab='students',sessionFilter='active'){
  const {group:g,students,sessions,homework,submissions}=detail;
  if(!g)return '<p>Група недоступна. Оновіть список груп.</p>';
  const editable=g.status==='active';
  let body='';
  if(tab==='students')body=`<div class="panel-head"><h3>Учні · ${students.length}</h3>${editable?`<button class="primary" data-action="group-add-student" data-id="${g.id}">＋ Додати учня</button>`:''}</div>`+table(['Учень','Прогрес','Відвідування','Проєкт',''],students.map(s=>`<tr><td><button class="text-button" data-action="group-profile" data-id="${s.id}">${escGroup(s.firstName)}</button></td><td>${s.progressPercent}%</td><td>${s.attendance.present+s.attendance.late}/${Object.values(s.attendance).reduce((a,b)=>a+b,0)}</td><td>${escGroup(s.projectTitle??'Поки немає')}</td><td>${editable?`<button class="danger-link" data-action="group-remove-student" data-id="${s.id}">Вилучити з групи</button>`:''}</td></tr>`));
  if(tab==='sessions')body=`${editable?`<button class="primary" data-action="group-new-session" data-id="${g.id}">＋ Запланувати заняття</button>`:''}`+sessionFilterButtons(sessionFilter,'data-group-session-filter')+table(['№ / Заняття','Дата і час · Київ','Статус','Відвідування','Домашня робота',''],visibleSessions(sessions,sessionFilter).map((s,i)=>`<tr><td><strong>${s.number??i+1}. ${escGroup(s.title)}</strong></td><td>${date(s.startsAt)}</td><td>${labels[s.status]??escGroup(s.status)}</td><td>${s.attendance.filter(a=>a.isCurrentMember!==false&&['present','late'].includes(a.status)).length}/${s.attendance.filter(a=>a.isCurrentMember!==false).length}</td><td>${escGroup(homework.find(h=>h.classSessionId===s.id&&h.status==='published')?.title??'Не призначено')}</td><td>${editable?`<button class="text-button" data-action="group-edit-session" data-id="${s.id}">Редагувати</button>`:''}</td></tr>`));
  if(tab==='attendance')body=table(['Заняття','Учень','Статус',''],sessions.flatMap(s=>s.attendance.map(a=>`<tr><td>${escGroup(s.title)}</td><td>${escGroup(a.studentName)}</td><td>${({present:'Присутній',late:'Запізнився',absent:'Відсутній',excused:'Поважна причина'})[a.status]??'Не підтверджено'}</td><td>${editable&&a.isCurrentMember!==false&&!['cancelled','archived'].includes(s.status)?`<button class="text-button" data-action="group-attendance" data-id="${s.id}" data-student="${a.studentId}">Змінити</button>`:''}</td></tr>`)));
  if(tab==='homework')body=`${editable?`<button class="primary" data-action="group-new-homework" data-id="${g.id}">＋ Домашня робота</button>`:''}`+table(['Завдання','Статус','Дедлайн','Надіслано'],homework.map(h=>`<tr><td>${escGroup(h.title)}</td><td>${({draft:'Чернетка',published:'Опубліковано',unpublished:'Знято з публікації',archived:'Архівовано'})[h.status]??escGroup(h.status)}</td><td>${date(h.dueAt)}</td><td>${submissions.filter(s=>s.homeworkId===h.id).length}</td></tr>`));
  if(tab==='projects')body=table(['Учень','Проєкт','Етап','Прогрес'],students.flatMap(s=>s.projects.map(p=>`<tr><td>${escGroup(s.firstName)}</td><td>${escGroup(p.title)}</td><td>${escGroup(p.stage.title)}</td><td>${p.completionPercent}%</td></tr>`)));
  return `<div class="group-workspace"><section class="group-hero panel"><div><span class="kicker">${escGroup(g.academicYear)} · ${g.status==='active'?'Активна':'Архівна'}</span><h2>${escGroup(g.name)}</h2><p>${escGroup(g.teacherName)} · ${escGroup(g.scheduleLabel)}</p><p>Старт: ${escGroup(g.startsOn)} · ${sessions.filter(s=>!['cancelled','archived'].includes(s.status)).length} створених занять · ${g.studentCount} учнів</p><p>Прогрес: ${g.progressPercent}% · Відвідування: ${g.attendanceRate}%</p></div><div class="hero-actions"><button class="secondary" data-action="group-edit" data-id="${g.id}">Редагувати</button>${editable?`<button class="danger-link" data-action="group-archive" data-id="${g.id}">Архівувати групу</button>`:''}</div></section>
    <div class="tabs" role="tablist">${[['students','Учні'],['sessions','Заняття'],['attendance','Відвідування'],['homework','Домашні роботи'],['projects','Проєкти']].map(([id,label])=>`<button role="tab" aria-selected="${id===tab}" class="${id===tab?'active':''}" data-group-tab="${id}">${label}</button>`).join('')}</div><section class="panel">${body}</section></div>`;
}
export function studentProfile(s){return `<div class="group-profile"><p>Група: ${escGroup(s.groupName)}</p><p>Прогрес: ${s.progressPercent}% · XP: ${s.xp}</p><p>Відвідування: ${s.attendance.present} присутніх · ${s.attendance.late} запізнень · ${s.attendance.absent} пропусків</p><p>Домашні роботи: ${s.homework.submitted}/${s.homework.assigned} · На доопрацюванні: ${s.homework.needsRevision}</p>${s.projects.map(p=>`<h3>${escGroup(p.title)}</h3><p>${escGroup(p.summary)} · ${p.completionPercent}%</p>`).join('')||'<p>Проєкт поки не створено</p>'}</div>`;}
export async function handleGroupAction(name,id,{api,detail,openModal,refresh,toast,studentId}){
  if(!['new-group','group-edit','group-archive','group-add-student','group-remove-student','group-profile','group-edit-session','group-new-session','group-attendance','group-new-homework'].includes(name))return false;
  if(name==='new-group'||name==='group-edit'){
    const directory=await api.groupDirectory(),group=name==='group-edit'?detail.group:{};
    openModal(name==='new-group'?'Нова група':'Редагувати групу',groupFields(group,directory.teachers),async form=>{
      const input=formInput(form);if(!input.weekdays.length)throw new Error('Оберіть щонайменше один день занять');
      if(name==='new-group')await api.createGroup(input);else await api.updateGroup(id,{...input,expectedVersion:group.version});
      return{message:name==='new-group'?'Групу створено':'Групу оновлено'};
    },name==='new-group'?'Створити групу':'Зберегти');
  }
  if(name==='group-archive')openModal('Архівувати групу',`<p>Учні, заняття й роботи групи «${escGroup(detail.group.name)}» збережуться в архіві.</p>`,async()=>{await api.archiveGroup(id,detail.group.version);return{message:'Групу архівовано'};},'Архівувати групу');
  if(name==='group-add-student'){
    const choices=detail.directory.students.filter(s=>s.groupId!==detail.group.id&&(!s.status||s.status==='active'));
    if(!choices.length){toast('Немає доступних учнів для додавання');return true;}
    openModal('Додати існуючого учня',`<label class="field"><span>Учень</span><select name="studentId">${choices.map(s=>`<option value="${escGroup(s.id)}">${escGroup(s.name)}${s.groupId?' · перенести з поточної групи':''}</option>`).join('')}</select></label><p class="privacy-note">Профіль учня не дублюється. У цій системі учень має одну поточну групу; історія навчання зберігається.</p>`,async form=>{const s=choices.find(s=>s.id===form.get('studentId'));await api.setGroupStudent(detail.group.id,s.id,true,s.version);return{message:'Учня додано до групи'};},'Додати учня');
  }
  if(name==='group-remove-student'){const s=detail.students.find(s=>s.id===id);openModal('Вилучити учня з групи',`<p>Профіль «${escGroup(s.firstName)}» та історія навчання збережуться.</p>`,async()=>{await api.setGroupStudent(detail.group.id,id,false,detail.directory.students.find(p=>p.id===id).version);return{message:'Учня вилучено з групи'};},'Вилучити з групи');}
  if(name==='group-profile'){const s=detail.students.find(s=>s.id===id);openModal(s.firstName,studentProfile(s),async()=>({message:'Профіль переглянуто'}),'Закрити');}
  if(name==='group-new-session'){
    const start=`${detail.group.startsOn}T${detail.group.time}`;
    openModal('Запланувати заняття',`<label class="field"><span>Тема</span><input name="title" required maxlength="160"></label><div class="form-grid"><label class="field"><span>Початок · Київ</span><input name="startsAt" type="datetime-local" value="${escGroup(start)}" required></label><label class="field"><span>Кінець · Київ</span><input name="endsAt" type="datetime-local" required></label></div>`,async form=>{await api.createClass({groupId:detail.group.id,courseId:detail.group.courseId,title:form.get('title'),localStartsAt:form.get('startsAt'),localEndsAt:form.get('endsAt')});return{message:'Заняття заплановано'};},'Запланувати');
  }
  if(name==='group-edit-session'){
    const s=detail.sessions.find(s=>s.id===id);
    const local=v=>{const p=new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Kyiv',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(v));return p.replace(' ','T')};
    openModal('Редагувати заняття',`<label class="field"><span>Назва</span><input name="title" required maxlength="160" value="${escGroup(s.title)}"></label><div class="form-grid"><label class="field"><span>Початок · Київ</span><input type="datetime-local" name="startsAt" required value="${local(s.startsAt)}"></label><label class="field"><span>Кінець · Київ</span><input type="datetime-local" name="endsAt" required value="${local(s.endsAt)}"></label></div><label class="field"><span>Статус</span><select name="status">${['scheduled','in_progress','completed','cancelled','archived'].map(status=>`<option value="${status}" ${(s.status==='rescheduled'?'scheduled':s.status)===status?'selected':''}>${labels[status]}</option>`).join('')}</select></label>`,async form=>{await api.updateClass(id,{title:form.get('title'),status:form.get('status'),localStartsAt:form.get('startsAt'),localEndsAt:form.get('endsAt')});return{message:'Заняття оновлено'};});
  }
  if(name==='group-attendance')openModal('Відвідування',`<label class="field"><span>Статус</span><select name="status"><option value="present">Присутній</option><option value="late">Запізнився</option><option value="absent">Відсутній</option><option value="excused">Поважна причина</option></select></label>`,async form=>{await api.saveOneAttendance(id,studentId,form.get('status'));return{message:'Відвідування збережено'};});
  if(name==='group-new-homework')openModal('Домашня робота',`<label class="field"><span>Заняття</span><select name="classSessionId">${detail.sessions.filter(s=>!['cancelled','archived'].includes(s.status)).map(s=>`<option value="${escGroup(s.id)}">${escGroup(s.title)}</option>`).join('')}</select></label><label class="field"><span>Назва</span><input name="title" required maxlength="180"></label><label class="field"><span>Завдання</span><textarea name="instructions" required maxlength="20000"></textarea></label>`,async form=>{await api.createHomework({groupId:detail.group.id,courseId:detail.group.courseId,classSessionId:form.get('classSessionId'),title:form.get('title'),instructions:form.get('instructions'),xpReward:100,status:'draft'});return{message:'Домашню роботу збережено'};});
  return true;
}
